@startuml name DX_GAME_Sequence_Diagram
title DX_GAME  3D描画シーケンス図
actor オブジェクトベース
participant ステート
participant アニメーション
participant モデル達
participant モデル

オブジェクトベース -> モデル: 初期設定
オブジェクトベース -> モデル達: モデル情報設定
オブジェクトベース -> アニメーション: アニメーション情報設定
モデル達 -> アニメーション: ポインタを渡す
オブジェクトベース -> ステート: 更新
ステート -> アニメーション: 動きの変更\nステートで変更
オブジェクトベース ->  アニメーション: 更新
アニメーション -> モデル達: 変更を加える
モデル達 -> モデル: 変更を加える\nステートで処理分け
モデル --> オブジェクトベース: 描画する
オブジェクトベース -> アニメーション : 削除
オブジェクトベース -> モデル達: 削除
モデル達 -> モデル: 削除
@enduml